// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR577boHXNhFLvrzGiZ7TXQVI6OyctO1E',
    appId: '1:1068104292309:web:4621473ec3aba4de9bcf5c',
    messagingSenderId: '1068104292309',
    projectId: 'oklah-mvp',
    authDomain: 'oklah-mvp.firebaseapp.com',
    storageBucket: 'oklah-mvp.firebasestorage.app',
    measurementId: 'G-PY8EK6BJK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwYeu7rcLGssRZLtuRQnn6MWGK7U6aMSg',
    appId: '1:1068104292309:android:14cdde2ad0b1d7f49bcf5c',
    messagingSenderId: '1068104292309',
    projectId: 'oklah-mvp',
    storageBucket: 'oklah-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx_WCOp-eesAGUPpz9ujn8eRD9NL-udcE',
    appId: '1:1068104292309:ios:69db42374cfaaad39bcf5c',
    messagingSenderId: '1068104292309',
    projectId: 'oklah-mvp',
    storageBucket: 'oklah-mvp.firebasestorage.app',
    iosBundleId: 'com.oklah.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx_WCOp-eesAGUPpz9ujn8eRD9NL-udcE',
    appId: '1:1068104292309:ios:00fe5229246161d79bcf5c',
    messagingSenderId: '1068104292309',
    projectId: 'oklah-mvp',
    storageBucket: 'oklah-mvp.firebasestorage.app',
    iosBundleId: 'com.oklah.oklah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR577boHXNhFLvrzGiZ7TXQVI6OyctO1E',
    appId: '1:1068104292309:web:44650b593e0b5d769bcf5c',
    messagingSenderId: '1068104292309',
    projectId: 'oklah-mvp',
    authDomain: 'oklah-mvp.firebaseapp.com',
    storageBucket: 'oklah-mvp.firebasestorage.app',
    measurementId: 'G-LQVLJ62PWH',
  );

}